"""Jarvis V2 protocol.

Everything that crosses a boundary (DB row, WS frame, model adapter, tool provider) is one of
these pydantic models. The web client's TypeScript types are generated from them
(`python -m jarvis_proto.schema`), so a change here is a change everywhere — by design.
"""

from jarvis_proto.events import (
    ClientMessage,
    ConversationDeleted,
    ConversationUpdated,
    GuardArmed,
    GuardConsumed,
    JudgeVerdict,
    MessageCreated,
    ModelCall,
    ModelDelta,
    ModelDone,
    PlanCreated,
    PlanStepDone,
    PlanStepStarted,
    Pong,
    RunCancelled,
    RunCancelRequest,
    RunCreateRequest,
    RunDone,
    RunEvent,
    RunFailed,
    RunInterrupted,
    RunQueued,
    RunResumed,
    RunStarted,
    RunWaitingUser,
    ServerEvent,
    Subscribe,
    ToolCallEvent,
    ToolConfirmRequest,
    ToolConfirmRequested,
    ToolConfirmResolved,
    ToolResultEvent,
    Unsubscribe,
    parse_client_message,
)
from jarvis_proto.ids import new_id
from jarvis_proto.messages import Message, Role, ToolCall, ToolResult, ToolResultKind
from jarvis_proto.runs import (
    Conversation,
    ConversationKind,
    ModelUsage,
    Plan,
    PlanStep,
    PlanStepStatus,
    Run,
    RunBudget,
    RunKind,
    RunStatus,
)
from jarvis_proto.settings import ModelSpec, Provider, RoleName, Settings
from jarvis_proto.tools import ToolSpec

__all__ = [
    "ClientMessage",
    "Conversation",
    "ConversationDeleted",
    "ConversationKind",
    "ConversationUpdated",
    "GuardArmed",
    "GuardConsumed",
    "JudgeVerdict",
    "Message",
    "MessageCreated",
    "ModelCall",
    "ModelDelta",
    "ModelDone",
    "ModelSpec",
    "ModelUsage",
    "Plan",
    "PlanCreated",
    "PlanStep",
    "PlanStepDone",
    "PlanStepStarted",
    "PlanStepStatus",
    "Pong",
    "Provider",
    "Role",
    "RoleName",
    "Run",
    "RunBudget",
    "RunCancelRequest",
    "RunCancelled",
    "RunCreateRequest",
    "RunDone",
    "RunEvent",
    "RunFailed",
    "RunInterrupted",
    "RunKind",
    "RunQueued",
    "RunResumed",
    "RunStarted",
    "RunStatus",
    "RunWaitingUser",
    "ServerEvent",
    "Settings",
    "Subscribe",
    "ToolCall",
    "ToolCallEvent",
    "ToolConfirmRequest",
    "ToolConfirmRequested",
    "ToolConfirmResolved",
    "ToolResult",
    "ToolResultEvent",
    "ToolResultKind",
    "ToolSpec",
    "Unsubscribe",
    "new_id",
    "parse_client_message",
]
